### ISSUE TITLE
BLE Characteristic gives an error:  Cannot read property '....' of undefined

### ISSUE THREAD

**Issue by koktaildotcom** [athombv/apps-sdk-issues#11]
I did a rewrite for the app `com.mi.flora` that can read out sensor information from the xiaomi mi flora devices. It all works fine except for the second (and all other) timeout to read sensor information again.

I've searched for hours through my code but it looks something in core. The second time i want the sensors to read (i've disconnected the BlePeripheral correctly the first time) i cannot call `write` to the `characteristic`. 

```
{ Error: Cannot read property '00001a0000001000800000805f9b34fb' of undefined 
   at Object.JSON.parse (/opt/homey-client/system/helpers/jsonfns.js:1:1190) 
   at JSON.parse (<anonymous>) 
   at jsonToObject (/opt/homey-client/system/helpers/jsonfns.js:1:1083) 
   at function.e.data.map.e (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1379) 
   at Array.map (<anonymous>) 
   at HomeyClient._onMessage (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1372) 
   at emitTwo (events.js:126:13) 
   at process.emit (events.js:214:7) 
   at emit (internal/child_process.js:762:12) 
   at _combinedTickCallback (internal/process/next_tick.js:142:11) 
 message: 'Cannot read property \'00001a0000001000800000805f9b34fb\' of undefined' } 
update device Philodendron erubescens 
(node:30900) UnhandledPromiseRejectionWarning: Error: Error: TypeError: Cannot read property 'read' of undefined 
   at /lib/MiFloraDriver.js:335:39 
   at <anonymous> 
   at process._tickCallback (internal/process/next_tick.js:189:7)
```

**Comment by koktaildotcom** [comment]
Can this be related to: https://github.com/athombv/homey-apps-sdk-issues/issues/7 ?

**Comment by WeeJeWel** [comment]
What ID is `00001a0000001000800000805f9b34fb`. Characteristic, service, etc?

**Comment by koktaildotcom** [comment]
Thats the data write characteristic.

**Comment by koktaildotcom** [comment]
If you have a 'xiaomi mi flora' device you can try this branch: https://github.com/koktaildotcom/homey-mi-flora/tree/feature/v2-rewrite?files=1

It accur the second time the sensor is read.

**Comment by koktaildotcom** [comment]
I've tried the branch on rc3 with all devices removed. Thought there could be a difference. But the same error occur.

**Comment by koktaildotcom** [comment]
Still an issue on rc4

**Comment by koktaildotcom** [comment]
Still an issue with rc7

**Comment by koktaildotcom** [comment]
@WeeJeWel any idea when you can take a look at this issue?

**Comment by koktaildotcom** [comment]
Still an issue with 2.0.0

**Comment by koktaildotcom** [comment]
The issue is verified by multiple alpha users.

**Comment by WeeJeWel** [comment]
We will address this issue in a 2.x release. Sorry for the delay!

**Comment by gerrit1968** [comment]
> We will address this issue in a 2.x release. Sorry for the delay!

@WeeJeWel any idea when the problem with the BLE will be solved?

**Comment by WeeJeWel** [comment]
This issue has been resolved in Homey v2.0.5. Thank you for reporting!

**Comment by koktaildotcom** [comment]
This is still an issue on Homey v2.0.5

**Comment by koktaildotcom** [comment]
Sorry, wrong issue.

**Comment by koktaildotcom** [comment]
This issue: https://github.com/athombv/homey-apps-sdk-issues/issues/7 is still a problem

**Comment by koktaildotcom** [comment]
Now i encounter this issue on Homey v2.0.5 (after PTP and reboot twice)

The log "already in realtime mode" is a test log to don't break on the error but notify that the service is cached and already in realtime mode. Can this be the problem? I can imagine that if you store an service in cache the state is static. But the BLE service of the Mi Flora is changed because you need to set the device in a 'real time data' state to be able to read data from the device.
```
return service.write(REALTIME_CHARACTERISTIC_UUID, Buffer.from([0xA0, 0x1F]), false).then(() => {
                        return service;
                    }).catch((error) => {
                        console.log(' ----- already in realtime mode!');
                        console.log(error);
                        return service;
                    });
```

Gives an error:
```
 ----- already in realtime mode!
{ Error: Cannot read property '00001a0000001000800000805f9b34fb' of undefined
    at Object.JSON.parse (/opt/homey-client/system/helpers/jsonfns.js:1:1190)
    at JSON.parse (<anonymous>)
    at jsonToObject (/opt/homey-client/system/helpers/jsonfns.js:1:1083)
    at function.e.data.map.e (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1379)
    at Array.map (<anonymous>)
    at HomeyClient._onMessage (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1372)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:762:12)
    at _combinedTickCallback (internal/process/next_tick.js:142:11)
  message: 'Cannot read property \'00001a0000001000800000805f9b34fb\' of undefined' }
```

**Comment by koktaildotcom** [comment]
I've been searching for a sollution for hours yesterday, but i've always get this exact error. I've tried to change the strategy into the 'foreach characteristic`. 

It looks like internally the `service` is saved but the service of the device is changed. The first iteration of the update sequence works 100% of the time. The seconds one fails 100% of the time.

Can you have a look at the core if you run the branch: https://github.com/koktaildotcom/homey-mi-flora/tree/feature/v2-rewrite?files=1?

**Comment by koktaildotcom** [comment]
```
return service.write(REALTIME_CHARACTERISTIC_UUID, Buffer.from([0xA0, 0x1F]), false).then(() => {
                        return service;
                    }).catch((error) => {
                        console.log(' ----- already in realtime mode!');
                        console.log(error);
                        return service;
                    });
```

At this point the `service` is a data service from the discovery. The `realtime characteristic` cannot be found on the object once it is stored internally so it looks to me.

**Comment by koktaildotcom** [comment]
Looks related to: https://github.com/athombv/homey-apps-sdk-issues/issues/73

**Comment by WeeJeWel** [comment]
I cannot seem to reproduce the issue. Could you please point me to a branch of your repository where this does occur?

**Comment by koktaildotcom** [comment]
1. Checkout: https://github.com/koktaildotcom/homey-mi-flora/tree/feature/v2-rewrite?files=1 and run the code.
1. Add a new device (or use an existing)
1. Wait until the second iteration kicks in, this is the point the error occur.

In lib/MiFloraDriver.js you van change the update interval (search for interval)

**Comment by WeeJeWel** [comment]
Fixed in v2.1.2-rc.4
